name: wasi_runtime
description: Experimental Dart host for loading and running WASI workloads.
version: 0.1.0
publish_to: none
repository: https://github.com/ishaf/wasi_runtime
issue_tracker: https://github.com/ishaf/wasi_runtime/issues

environment:
  sdk: ^3.11.0

resolution: workspace

executables:
  dart_wasi_host: dart_wasi_host

dependencies:
  crypto: ^3.0.7
  wasd:
    git:
      url: https://github.com/ishafiul/wasd.git
      ref: 576d206560ddf3d6d6244767230d9d5a352a3ce2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
